### PR TITLE
Fix location of sklearn's DistanceMetric

### PR DESCRIPTION
**Pull request by dachengx**
Resolve: https://github.com/XENONnT/GOFevaluation/issues/47

### CODE REVIEW

**Comment by hammannr** [comment]
Hey @dachengx , sorry for the late reply -- I somehow overlooked this PR. I think a more sensible solution to this would be to update the location of the DistanceMetric class in sklearn. Could you quickly check whether this also solves your issue?

**Comment by matteoguida** [comment]
Ehi @hammannr, why not to merge this? I also had the same issue. The current proposed file change seems good to me.

**Comment by dachengx** [comment]
> Hey @dachengx , sorry for the late reply -- I somehow overlooked this PR. I think a more sensible solution to this would be to update the location of the DistanceMetric class in sklearn. Could you quickly check whether this also solves your issue?

What do you mean by 'update the location'? :)

**Comment by hammannr** [comment]
> > Hey @dachengx , sorry for the late reply -- I somehow overlooked this PR. I think a more sensible solution to this would be to update the location of the DistanceMetric class in sklearn. Could you quickly check whether this also solves your issue?
> 
> What do you mean by 'update the location'? :)

Ah sorry not very accurate. What I meant is that `DistantMetric` is now in `sklearn.metrics` instead of `sklearn.nighbours`. So simply changing this should solve the problem. If this fix works for your @dachengx I would merge it with this fix.

**Comment by dachengx** [comment]
> Ah sorry not very accurate. What I meant is that `DistantMetric` is now in `sklearn.metrics` instead of `sklearn.nighbours`. So simply changing this should solve the problem. If this fix works for your @dachengx I would merge it with this fix.

Yes, current PR works.

**Review by hammannr — APPROVED** [review]

**Pull request merged**
